# Site
repository: VNOpenAI-Profiles/phidch
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Personal info
name: Phi Dao-Cu-Hung
title: AI Engineer
email: phi9b2@gmail.com
# phone: null
cv   : "resume.pdf"
website: https://web.vnopenai.org/phidch/

# Social links
#twitter_username: jekyllrb
github_username:  phidch
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  An AI Engineer with a background of electronics and control theory, robot system. I enjoy learning new things everyday and pratice is my prefer.
  
  **My interest includes:**

    + Computer vision
    + Self-driving car
    + Applied machine learning

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# Publication
# publication_title: Publications

# More Section
more_title: My Hobbies
more_content: | # this will include new lines to allow paragraphs
  I love playing guitar and singing, spending time with my family members and playing games with friends every weedkend. 

# Footer
footer_show_references: true

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "makefile",
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
